Improvements1
HardcodedDream/angular-react-starter pull request #1
Opened 2022-08-13 07:55 UTC by HardcodedDream

edited code following the results of the first review

2022-08-13 08:27 UTC, HardcodedDream commented
Hello, @dmitry-mightydevops,

thank you for the initial code review. I've attempted to make improvements you've mentioned in the summary. Now you can find all the changes in this pull request. Please let me know if smth. needs enhancement yet. 

Thank you in advance

2022-08-17 23:11 UTC, dmitry-mightydevops requested changes
Max - it's better! Let's work out few quirks

2022-08-17 23:11 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
github token always available to you - no need to pass any Personal access tokens here
https://docs.github.com/en/actions/security-guides/automatic-token-authentication

2022-08-17 23:11 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          completion_timestamp=$(echo $jobs | jq -r .jobs[-2].completed_at)
so what happens if you change structure of your jobs and the index change?

2022-08-17 23:11 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          completion_timestamp=$(echo $jobs | jq -r .jobs[-2].completed_at)
you really can get current time (as the value for the completion) at this step without making a 2nd API call against jobs[-2]

2022-08-17 23:11 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
let's simplify the duration calculation -it's still TOO complex and long implementation. 
you just need to find the start time of your first job and at the end just calculate the diff between 2 time points.

2022-08-17 23:11 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
no need to pass the token this way. GITHUB_TOKEN is always available inside any job.

2022-08-17 23:11 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          commit_response=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/commits/${{ github.sha }})
no need to call for API. Github makes it available to you
github.event.commits[0].author.name

2022-08-17 23:11 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
>            from: HardcodedDream
don't hardcode the user name. Take it from github vars you get inside github actions when you job runs.

2022-08-18 14:49 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +    branches: [master,improvements1]
got it and fixed

2022-08-18 15:00 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +    name: node-test
I've followed your advise while editing names in "test" and "build" jobs. The rest is not really concise, I guess, but both "deploy" and "push-notifications", especially the latter one, consist of steps that don't appear to be as straightforward as test/build actions. Some steps are not self-explanatory and need clarification of what they are intended to. Basically, I got your message in this case

2022-08-18 15:03 UTC, HardcodedDream commented on .github/workflows/ci.yaml
>    app-build-deploy:
fixed as "app-build-deploy" was split into "build" and "deploy" jobs. The latter one needs "build" to be complete successfully

2022-08-18 15:18 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
regarding 1st point

GITHUB_TOKEN was initialized as an env variable on the top of configuration. Other occurrences / references to the same value are no longer present

regarding 2nd point

job_outcomes.txt is a part of functionality needed to find out whether any of core jobs has failed or not. The calculation of execution time is pretty clear to me, I've just changed completion time from reading "completion_at" timestamp to the current time output on a Linux system. So, my aim is to figure out status of core jobs, so that a user can be notified if some job has failed. It's about job status to determine what event to notify the user on as we can't just request status of the workflow (it's "null" while actions are going on) rather than just about duration.

2022-08-18 15:24 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +          completion_timestamp=$(echo $jobs | jq -r .jobs[-2].completed_at)
each job depends on the previous one. Definitely changing order will break the workflow. Sure, I understand your remark, but reschuffling jobs don't make any sense if pipeline has configuration as it is. I changed however this line to get completion timestamp from "date" command output

2022-08-18 15:25 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
fixed, initialized GITHUB_TOKEN as an env variable

2022-08-18 15:32 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +          commit_response=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/commits/${{ github.sha }})
it works only if workflow run was triggered by "push" event. My today's commits are automatically labeled as pull requests rather than pushes. There are no "commits" and following properties for events which triggers are pull requests     

https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types#pullrequestevent

as both email and user name are to be empty when pull request is fired, api call was not removed

2022-08-18 15:39 UTC, HardcodedDream commented
first of all, thank you kindly for your feedback. I've added personal comments, including those explaining some perhaps weird stuff in the pipeline code. This pull request (I believe) is ready for the next review

2022-08-18 22:46 UTC, dmitry-mightydevops requested changes

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
so essentially speaking you just renaming the value. That doesn't add anything to the table. So better stick with secrets.GITHUB_TOKEN where you need it, as this is known to devops engineers who would maintain your solution.

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
>          node-version: [16.x]
so we have hardcoded the value. The downside is that if developers use a different version (typically defined in the package.json) your pipeline uses a different node/npm. That could lead to side effects. OR devs will be modifying your pipeline which could lead to side effects as well. 

So let's read the node version from the package.json and use the version devs are using.

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +      - name: install dependencies
`install` is short, clear and concise.

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +        run: npm run build --if-present
you support both feature/branch and master branch via PR. However production (in master) should use a different npm cli for the build compared with dev - ket's use if and pass a proper CLI call so that your pipeline supports the dev build and prod build.

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
>        - name: install Angular module
use similar names, don't diverge. That helps traverse the pipeline. Longer names makes reading hard. `install` is totally fine. A good devops engineer pays attention to implementation, therefore too much text == distraction for us.

So naming = short and concise.
If you want explain something valuable to other devops engineers - then use comment boxes but don't make long names/ids etc. I.e name should not be used as inline documentation

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +      - name: build an Angular app
use short semantic names. 
`build` no need to say we're building angular app. we already know you build an angular app :)

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +        run: ng build --configuration production --base-href https://github.com/HardcodedDream/angular-react-starter
prefer multiline - they help readability.

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          name: deploy_assets
very good ! :)

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +    runs-on: ubuntu-latest
don't make too much spacing. Separate jobs, steps, but not runson, needs etc.

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_VERSION
push also latest tag. which should point to the same SHA revision.

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +    needs: [test, build, deploy]
that is muuuch easier to read and is clean!

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          echo ::set-output name=user_email::${user_email}
find that info without making API call

2022-08-18 22:46 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          echo ::set-output name=user_email::${user_email}
that step is not necessary - github actions provide info about commit.

2022-08-19 15:34 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
well, changed var name to GITHUB_TOKEN to avoid any confusion

2022-08-19 15:35 UTC, HardcodedDream commented on .github/workflows/ci.yaml
>          node-version: [16.x]
fixed. I had to add version to `package.json` for test pusposes as it was missing there

2022-08-19 15:36 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +      - name: install dependencies
fixed

2022-08-19 15:37 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +        run: npm run build --if-present
not sure that this time it looks better, but I guess it's fixed

2022-08-19 15:37 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +        run: ng build --configuration production --base-href https://github.com/HardcodedDream/angular-react-starter
fixed

2022-08-19 15:38 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_VERSION
fixed

2022-08-19 15:47 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +          echo ::set-output name=user_email::${user_email}
so, after few hours in search for any relevant ideas the following was found: 

https://github.com/rlespinasse/git-commit-data-action

much easier than a method described [here](https://stackoverflow.com/questions/70730827/github-actions-get-pr-author-email-address)

so, pull request event doesn't have something like email property. User name can be read from `github.actor`. The same does not appear to exist if someone needs email of a guy who triggered workflow by his/her pull request. May be my suggestion is false. Then just give a hint what GitHub docs reveal that information. So far it works with an extra action

2022-08-19 15:51 UTC, HardcodedDream commented
Thank you once again. Pipeline code was modified, now it's available for the next review.

Have a perfect day and enjoy your weekend

2022-08-23 02:02 UTC, dmitry-mightydevops requested changes

2022-08-23 02:02 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +        if: steps.evaluate-outcome.outputs.job_name != '<success>'
pls read how to use failure()
https://docs.github.com/en/actions/learn-github-actions/expressions#failure

2022-08-23 02:02 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +        if: steps.evaluate-outcome.outputs.job_name == '<success>'
same issue
https://docs.github.com/en/actions/learn-github-actions/expressions#failure

2022-08-23 02:02 UTC, dmitry-mightydevops commented on .github/workflows/ci.yaml
> +          body: "The workflow \"${{ github.workflow }}\" of the repository \"${{ github.repository }}\" has finished successfully in${{ steps.process-timestamps.outputs.hours }}${{ steps.process-time
use multiline. single long one-liners are hard to read or maintain.

2022-08-23 05:38 UTC, closed without merging

2022-08-23 12:49 UTC, HardcodedDream commented on .github/workflows/ci.yaml
> +  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
![image](https://user-images.githubusercontent.com/110806571/186161995-b637e60d-0750-49f5-be73-5cc1931449cc.png)

answer:

![image](https://user-images.githubusercontent.com/110806571/186162065-3341928e-bf0a-4e51-8abc-18b23ab5ccc1.png)